version: '3.7'

services:
  ts-node-docker:
    user : "newuser"
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    volumes:
      - ./src:/home/newuser/app/src
      - ./nodemon.json:/home/newuser/app/nodemon.json
    expose:
      - '3000'
    deploy:
      replicas: 4
    command: npm start
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
    - '8080:80'
    depends_on:
    - ts-node-docker